### ISSUE TITLE
Use prefect flow for workflow manager

### ISSUE THREAD

**Issue by JacksonMaxfield** [AllenCellModeling/cookiecutter-stepworkflow#11]
## Use Case
*Please provide a use case to help us understand your request in context*
Let people write there own dags if they want. _Maybe_ add a `construct_dag` bin script that attempts to construct the prefect DAG for them. But regardless it should all be handled by prefect instead of a single list of steps

**Comment by donovanr** [comment]
this is redundant with #6 i think?  lets pick one and run with it.

**Comment by JacksonMaxfield** [comment]
Agree it is redundant. Closing #6 as I like the idea of `construct_dag` even if it is hard to do. At the very least allowing people to write their own prefect workflows by default is closer to what the team wants.

**Comment by JacksonMaxfield** [comment]
Weird psuedo-code that everyone agreed on:
```python
class Norm.run(data):
	with Flow() as flow:
		processed = data.map(_single_process_function)

	state = flow.run(executor=DaskExecutor("some_gpu_address"))

	return state.get_task_result("processed")

```

bin/all.py

```python
from steps import Raw, QC,

raw = Raw(check_exists=True)
qc = QC(check_exists=False)
norm = Norm(check_exists=False)


with Flow() as flow:
	raw_data = raw.run()
	qc_data = qc.run(raw_data)
	normed_data = norm.run(qc_data)


flow.run(excutor=DaskExecutor("some_cpu_address"))

```

**Comment by donovanr** [comment]
just a note that we need to check how `Fire` handles functions that don't return `None`.  Don't want to break e.g. `project_name raw run` when we accommodate flow style data passing.

Seems like we should be able to write a "catcher" decorator and call it in `cli.py` that runs the step sun functions but catches and eats returned values so  the step-wise cli is still clean.
