### ISSUE TITLE
Add 'pdb' option to run commands

### ISSUE THREAD

**Issue by cdw** [AllenCellModeling/cookiecutter-stepworkflow#21]
Add a 'pdb' option, particularly to 'run', that drops the user into a pdb instance on an error during execution.

**Comment by JacksonMaxfield** [comment]
I would say this is the exact reason that we have the "protected arguments"  (that aren't really protected).

I personally believe that you as the developer should do this with the `debug` kwarg. This way you can simply do `project step run --debug`? Does that work or no?

**Comment by cdw** [comment]
That _sounds_ good but I'm not sure how I'd go about implementing it. Does that mean that I'd add a flag to the `run` method that looks for a `debug` run and then executes under `pdb`?

**Comment by JacksonMaxfield** [comment]
Just another argument to `run`. But yep. If `debug` is true then start up `pdb`

**Comment by cdw** [comment]
Ah, this makes more sense to me after reading the [docstring for run in datastep](https://github.com/AllenCellModeling/datastep/blob/99bc7c680bd91c0b82ad861d559430ab945ecce3/datastep/step.py#L339).
